package(
    default_visibility = [
        "//python:__subpackages__",
    ],
)
# Utils
py_library(
    name = "ListNode",
    srcs = ["ListNode.py"],
)

py_library(
    name = "LinkedList",
    srcs = ["LinkedList.py"],
    deps = [
        ":ListNode",
    ],
)
